### ISSUE TITLE
ERROR: Service 'jfrog-artifactory-training' failed to build : Build failed

### ISSUE THREAD

**Issue by SujjithS** [conan-io/training#112]
15:54:51,627 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:54:51,635 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7867e448 - Registering current configuration as safe fallback point

2023-03-11T15:54:53.414Z [jfrou] [INFO ] [58620e417863958e] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 90 seconds with 2m0s timeout
2023-03-11T15:54:54.761Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory, attempt number 40
2023-03-11T15:54:54.778Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory attempt number 40 failed with code : ECONNREFUSED
2023-03-11T15:54:55.230Z [[35[jfob ] [INFO ] [24df8ccb240867de] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 90 seconds with 2m0s timeout [startup]
2023-03-11T15:54:55.436Z [jfmd ] [INFO ] [                ] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 100 seconds with 2m0s timeout [init]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
2023-03-11T15:54:57.197Z [jfevt] [INFO ] [09d33188751138ec] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 95 seconds with 2m0s timeout [startup]
2023-03-11T15:54:57.518Z [jfint] [INFO ] [3a8f5ccd2800c654] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 80 seconds with 2m0s timeout [startup]
2023-03-11T15:54:59.013Z [jfrou] [INFO ] [58620e417863958e] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 95 seconds with 2m0s timeout
2023-03-11T15:55:00.131Z [jfmd ] [INFO ] [                ] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 105 seconds with 2m0s timeout [init]
2023-03-11T15:55:00.449Z [[35[jfob ] [INFO ] [24df8ccb240867de] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 95 seconds with 2m0s timeout [startup]
2023-03-11T15:55:01.553Z [jfint] [INFO ] [3a8f5ccd2800c654] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 85 seconds with 2m0s timeout [startup]
2023-03-11T15:55:03.783Z [jfevt] [INFO ] [09d33188751138ec] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 100 seconds with 2m0s timeout [startup]
2023-03-11T15:55:04.434Z [jfrou] [INFO ] [58620e417863958e] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 100 seconds with 2m0s timeout
2023-03-11T15:55:01.654Z [jfrt ] [INFO ] [32d92e2d84b230b3] [o.a.c.h.HaNodeProperties:65   ] [Catalina-utility-1  ] - Artifactory is running in non-clustered mode.
2023-03-11T15:55:05.188Z [[35[jfob ] [INFO ] [24df8ccb240867de] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 100 seconds with 2m0s timeout [startup]
2023-03-11T15:55:06.048Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory, attempt number 50
2023-03-11T15:55:06.093Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory attempt number 50 failed with code : ECONNREFUSED
2023-03-11T15:55:06.147Z [jfrt ] [INFO ] [32d92e2d84b230b3] [tifactoryHomeConfigListener:85] [Catalina-utility-1  ] - Resolved Home: '/opt/jfrog/artifactory
2023-03-11T15:55:06.556Z [jfint] [INFO ] [3a8f5ccd2800c654] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 90 seconds with 2m0s timeout [startup]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
2023-03-11T15:55:10.033Z [jfmd ] [INFO ] [                ] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 115 seconds with 2m0s timeout [init]
2023-03-11T15:55:10.193Z [[35[jfob ] [INFO ] [24df8ccb240867de] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 105 seconds with 2m0s timeout [startup]
2023-03-11T15:55:11.701Z [jfint] [INFO ] [3a8f5ccd2800c654] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 95 seconds with 2m0s timeout [startup]
2023-03-11T15:55:12.459Z [jfevt] [INFO ] [09d33188751138ec] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 110 seconds with 2m0s timeout [startup]
2023-03-11T15:55:13.367Z [jfrou] [INFO ] [58620e417863958e] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 110 seconds with 2m0s timeout
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
2023-03-11T15:55:14.824Z [jfmd ] [ERROR] [                ] [keys.go:23                    ] [main                ] [] - Failed resolving master key: failed resolving 'shared.security.masterKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/master.key
goroutine 1 [running]:
runtime/debug.Stack()
	/src/runtime/debug/stack.go:24 +0x65
jfrog.com/jfrog-go-commons/v7/pkg/log.(*standardLogger).Panicfc(0xc000298210, {0x1b1a2b0, 0xc000458db0}, {0xc0004720a0, 0x96}, {0x0, 0x0, 0x0})
	goroot/pkg/mod/jfrog.com/jfrog-go-commons/v7@v7.62.0/pkg/log/standard_logger.go:95 +0xd2
jfrog.com/metadata/v7/services/common.MustResolveSecurityKeys({0x1b1a2b0, 0xc000458db0}, {0x1b1ede8, 0xc0003bff40}, {0x1b252e0, 0xc000298210?})
	jfrog.com/metadata/v7@v7.53.0/services/common/keys.go:23 +0x1ca
main.main()
	jfrog.com/metadata/v7@v7.53.0/metadata.go:31 +0x345
 [init]
panic: Failed resolving master key: failed resolving 'shared.security.masterKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/master.key
goroutine 1 [running]:
runtime/debug.Stack()
	/src/runtime/debug/stack.go:24 +0x65
jfrog.com/jfrog-go-commons/v7/pkg/log.(*standardLogger).Panicfc(0xc000298210, {0x1b1a2b0, 0xc000458db0}, {0xc0004720a0, 0x96}, {0x0, 0x0, 0x0})
	goroot/pkg/mod/jfrog.com/jfrog-go-commons/v7@v7.62.0/pkg/log/standard_logger.go:95 +0xd2
jfrog.com/metadata/v7/services/common.MustResolveSecurityKeys({0x1b1a2b0, 0xc000458db0}, {0x1b1ede8, 0xc0003bff40}, {0x1b252e0, 0xc000298210?})
	jfrog.com/metadata/v7@v7.53.0/services/common/keys.go:23 +0x1ca
main.main()
	jfrog.com/metadata/v7@v7.53.0/metadata.go:31 +0x345

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00047e600?, 0x0?})
	goroot/pkg/mod/github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0002a0300, {0xc00047e600, 0x2e6})
	goroot/pkg/mod/github.com/rs/zerolog@v1.27.0/event.go:156 +0x2a5
github.com/rs/zerolog.(*Event).Msgf(0xc0002a0300, {0xc000472140?, 0x2862cf0?}, {0xc0006efd28?, 0x2865880?, 0xc000472140?})
	goroot/pkg/mod/github.com/rs/zerolog@v1.27.0/event.go:129 +0x4e
jfrog.com/jfrog-go-commons/v7/pkg/log.(*standardLogger).logMessage(0xc000298210, {0x1b1a2b0, 0xc000458db0}, 0x79?, {0xc000472140, 0x99}, {0xc0006efd28, 0x1, 0x1})
	goroot/pkg/mod/jfrog.com/jfrog-go-commons/v7@v7.62.0/pkg/log/standard_logger.go:118 +0x245
jfrog.com/jfrog-go-commons/v7/pkg/log.(*standardLogger).Panicfc(0xc000298210, {0x1b1a2b0, 0xc000458db0}, {0xc0004720a0, 0x96}, {0x0, 0x0, 0x0})
	goroot/pkg/mod/jfrog.com/jfrog-go-commons/v7@v7.62.0/pkg/log/standard_logger.go:96 +0x1dc
jfrog.com/metadata/v7/services/common.MustResolveSecurityKeys({0x1b1a2b0, 0xc000458db0}, {0x1b1ede8, 0xc0003bff40}, {0x1b252e0, 0xc000298210?})
	jfrog.com/metadata/v7@v7.53.0/services/common/keys.go:23 +0x1ca
main.main()
	jfrog.com/metadata/v7@v7.53.0/metadata.go:31 +0x345
2023-03-11T15:55:15.197Z [[35[jfob ] [INFO ] [24df8ccb240867de] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 110 seconds with 2m0s timeout [startup]
2023-03-11T15:55:15.298Z [jfrt ] [INFO ] [32d92e2d84b230b3] [o.a.c.h.ArtifactoryHome:1004  ] [Catalina-utility-1  ] - Setting '' to system property 'spring.profiles.active'
2023-03-11T15:55:16.262Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory, attempt number 60
2023-03-11T15:55:16.310Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory attempt number 60 failed with code : ECONNREFUSED
2023-03-11T15:55:16.705Z [jfint] [INFO ] [3a8f5ccd2800c654] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 100 seconds with 2m0s timeout [startup]
2023-03-11T15:55:17.464Z [jfevt] [INFO ] [09d33188751138ec] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 115 seconds with 2m0s timeout [startup]
2023-03-11T15:55:17.658Z [jfrt ] [INFO ] [32d92e2d84b230b3] [o.a.c.h.ArtifactoryHome:1004  ] [Catalina-utility-1  ] - Setting '' to system property 'spring.profiles.active'
2023-03-11T15:55:17.958Z [jfrt ] [INFO ] [                ] [o.j.c.w.FileWatcher:146       ] [file-watcher-poller ] - Starting watch of folder configurations
2023-03-11T15:55:18.369Z [jfrou] [INFO ] [58620e417863958e] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 115 seconds with 2m0s timeout
2023-03-11T15:55:18.390Z [jfrt ] [WARN ] [32d92e2d84b230b3] [c.z.h.u.DriverDataSource:70   ] [Catalina-utility-1  ] - Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
2023-03-11T15:55:20.229Z [[35[jfob ] [INFO ] [24df8ccb240867de] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 115 seconds with 2m0s timeout [startup]
2023-03-11T15:55:21.709Z [jfint] [INFO ] [3a8f5ccd2800c654] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 105 seconds with 2m0s timeout [startup]
2023-03-11T15:55:22.142Z [jfevt] [FATAL] [09d33188751138ec] [bootstrap.go:144              ] [main                ] [                ] - Failed resolving master key: failed resolving 'shared.security.masterKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/master.key [startup]
2023-03-11T15:55:23.404Z [jfrou] [INFO ] [58620e417863958e] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 120 seconds with 2m0s timeout
2023-03-11T15:55:23.441Z [jfrou] [FATAL] [58620e417863958e] [bootstrap.go:99               ] [main                ] [] - Failed resolving master key: failed resolving 'shared.security.masterKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/master.key
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
2023-03-11T15:55:24.963Z [[35[jfob ] [FATAL] [24df8ccb240867de] [bootstrap.go:105              ] [main                ] [] - Failed resolving master key: failed resolving 'shared.security.masterKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/master.key [startup]
2023-03-11T15:55:26.518Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory, attempt number 70
2023-03-11T15:55:26.527Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory attempt number 70 failed with code : ECONNREFUSED
2023-03-11T15:55:27.042Z [jfint] [INFO ] [3a8f5ccd2800c654] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 110 seconds with 2m0s timeout [startup]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
2023-03-11T15:55:29.989Z [jfac ] [INFO ] [ec677504b51a9914] [licationContextInitializer:162] [Catalina-utility-2  ] - Access (jfac) service initialization started. Version: 7.59.4 Revision: 75904900 PID: 4967 Home: /opt/jfrog/artifactory
2023-03-11T15:55:30.581Z [jfac ] [INFO ] [ec677504b51a9914] [o.j.a.AccessApplication:55    ] [Catalina-utility-2  ] - Starting AccessApplication v7.59.4 using Java 17.0.3 on f7b66c47c5c0 with PID 4967 (/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-application-7.59.4.jar started by artifactory in /opt/jfrog/artifactory/var)
2023-03-11T15:55:30.588Z [jfac ] [INFO ] [ec677504b51a9914] [o.j.a.AccessApplication:680   ] [Catalina-utility-2  ] - No active profile set, falling back to 1 default profile: "default"
2023-03-11T15:55:32.044Z [jfint] [INFO ] [3a8f5ccd2800c654] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 115 seconds with 2m0s timeout [startup]
2023-03-11T15:55:33.399Z [jfrt ] [INFO ] [32d92e2d84b230b3] [.BasicConfigurationManager:186] [Catalina-utility-1  ] - Artifactory (jfrt) service initialization started. Version: 7.49.3 Revision: 74903900 PID: 4967 Home: /opt/jfrog/artifactory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
2023-03-11T15:55:36.627Z [jfint] [FATAL] [3a8f5ccd2800c654] [bootstrap.go:146              ] [main                ] [                ] - Failed resolving master key: failed resolving 'shared.security.masterKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/master.key [startup]
2023-03-11T15:55:36.738Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory, attempt number 80
2023-03-11T15:55:36.765Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory attempt number 80 failed with code : ECONNREFUSED
2023-03-11T15:55:38.447Z [jfrt ] [INFO ] [32d92e2d84b230b3] [o.j.s.c.KeyUtils:108          ] [Catalina-utility-1  ] - Master key is missing. Pending for 5 seconds with 60 seconds timeout
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
2023-03-11T15:55:43.462Z [jfrt ] [INFO ] [32d92e2d84b230b3] [o.j.s.c.KeyUtils:108          ] [Catalina-utility-1  ] - Master key is missing. Pending for 5 seconds with 60 seconds timeout
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
2023-03-11T15:55:47.023Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory, attempt number 90
2023-03-11T15:55:47.075Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory attempt number 90 failed with code : ECONNREFUSED
2023-03-11T15:55:48.473Z [jfrt ] [INFO ] [32d92e2d84b230b3] [o.j.s.c.KeyUtils:108          ] [Catalina-utility-1  ] - Master key is missing. Pending for 5 seconds with 60 seconds timeout
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8082: Connection refused
Timed out waiting for Artifactory
The command '/bin/sh -c /scripts/bootstrap-artifactory-config.sh' returned a non-zero code: 152
ERROR: Service 'jfrog-artifactory-training' failed to build : Build failed

Post running docker-compose up -d, I am getting the above connection refused error. Can anyone help me how to sort this out?

**Comment by memsharded** [comment]
It is difficult to know. 
I have just tested it, and it worked (Windows Docker Desktop 4.17.0)

In any case, we have added some notes in the Academy, because the training is for 1.X, but Conan 2.0 has been already released. The recommended way to learn Conan would be the new tutorial in: https://docs.conan.io/2/tutorial.html

**Comment by SujjithS** [comment]
Mine is an ubuntu machine and for some reason it gives
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (7) Failed to connect to localhost port 8082: Connection refused
Is it because the port is closed? How can I make this work? I wish to complete the training with all the given instructions

**Comment by memsharded** [comment]
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (7) Failed to connect to localhost port 8082: Connection refused
Is it because the port is closed? How can I make this work? I wish to complete the training with all the given instructions

Could it be that your machine has some firewall or other tool that could be restricting ports or something like that? Is your machine provisioned by IT of your company?

**Comment by SujjithS** [comment]
@memsharded This is my personal laptop

**Comment by memsharded** [comment]
It seems something very specific to your laptop. Didn't you configure any iptables/firewall in the past? Is it possible that you have some other application running on ports 8081 and 8082?

**Comment by SujjithS** [comment]
@memsharded Below is what is see on ports 8081 & 8082
![image](https://user-images.githubusercontent.com/81348122/224651361-3980a0d9-fe6a-4c16-8c44-0f9a3577a2d2.png)

**Comment by memsharded** [comment]
That is a good hint. The port 8081 is busy with that ``tproxy``, which is a network thing, seems also related to firewall/iptables, and it is most likely causing the issue, because that is the default port of the tomcat server, shouldn't be busy.
I don't know much about Linux sysadmin, no idea how to do it, but releasing that port sounds the way to go.

**Comment by SujjithS** [comment]
Okay. I will make that port open.
![image](https://user-images.githubusercontent.com/81348122/224660895-54f6c8fa-26ab-4187-a058-c7f75b1976f0.png)
Below image implies it is open now.
![image](https://user-images.githubusercontent.com/81348122/224661896-53be8187-3da9-4441-94be-759d1c1f0a53.png)

But then it gives the same error
![image](https://user-images.githubusercontent.com/81348122/224661135-78b8f0db-8afa-41cf-9ede-4165e8f3fb0f.png)
